# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 19:22
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogroll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'Maximum 250 characters.', max_length=250)),
                ('url', models.URLField()),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Blogroll',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'Maximum 250 characters.', max_length=250)),
                ('slug', models.SlugField(help_text=b'Suggested value automatically generated from title. Must be unique.', unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, b'Live'), (2, b'Draft'), (3, b'Hidden')], default=1)),
                ('hero_image', models.ImageField(blank=True, help_text=b'Required size = 1440 x 378.', null=True, upload_to=b'uploads/')),
                ('title', models.CharField(help_text=b'Maximum 250 characters.', max_length=250)),
                ('excerpt', ckeditor.fields.RichTextField(blank=True, help_text=b'A short summary of the entry. Optional.')),
                ('body', ckeditor.fields.RichTextField(blank=True)),
                ('pub_date', models.DateTimeField(default=datetime.datetime.now)),
                ('slug', models.SlugField(help_text=b'Suggested value automatically generated from title.', max_length=250, unique_for_date=b'pub_date')),
                ('enable_comments', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categories', models.ManyToManyField(to='blog.Category')),
            ],
            options={
                'ordering': ['-pub_date'],
                'verbose_name_plural': 'Entries',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text=b'Maximum 250 characters.', max_length=250)),
                ('slug', models.SlugField(help_text=b'Suggested value automatically generated from title. Must be unique.', unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['title'],
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.AddField(
            model_name='entry',
            name='tags',
            field=models.ManyToManyField(to='blog.Tag'),
        ),
    ]
