# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-29 18:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogroll',
            name='title',
            field=models.CharField(help_text='Maximum 250 characters.', max_length=250),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(help_text='Maximum 250 characters.', max_length=250),
        ),
        migrations.AlterField(
            model_name='entry',
            name='excerpt',
            field=ckeditor.fields.RichTextField(blank=True, help_text='A short summary of the entry. Optional.'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Required size = 1440 x 378.', null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='slug',
            field=models.SlugField(help_text='Suggested value automatically generated from title.', max_length=250, unique_for_date='pub_date'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='status',
            field=models.IntegerField(choices=[(1, 'Live'), (2, 'Draft'), (3, 'Hidden')], default=1),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(help_text='Maximum 250 characters.', max_length=250),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(help_text='Maximum 250 characters.', max_length=250),
        ),
    ]
