# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-19 19:08
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20170829_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='body',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='excerpt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text=b'A short summary of the entry. Optional.'),
        ),
    ]
