# Generated by Django 2.2 on 2019-07-21 17:25

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20171219_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='excerpt',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, help_text='A short summary of the entry. Optional.'),
        ),
    ]
