# Generated by Django 3.2.15 on 2022-10-12 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190721_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blogroll',
        ),
    ]
