web:
  container_name: web
  restart: always
  build: ./web/
  expose:
     - "8000"
  links:
    - postgres:postgres
    - redis:redis
  env_file: env
  volumes:
    - ./web:/data/web
  command: /usr/bin/gunicorn --timeout 300 wsgi:application -w 2 -b 0.0.0.0:8000
  working_dir: /data/web/projectfiles

nginx:
  container_name: nginx
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
    - "443:443"
  volumes_from:
    - web
  volumes:
    - /docker-volumes/etc/letsencrypt:/etc/letsencrypt/
  links:
    - web:web

postgres:
  container_name: postgres
  restart: always
  image: postgres:latest
  volumes_from:
    - data
  volumes:
    - ./postgres/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  env_file:
    - env
  expose:
    - "5432"

redis:
  container_name: redis
  restart: always
  image: redis:latest
  expose:
    - "6379"

data:
  container_name: data
  restart: always
  image: alpine
  volumes:
    - /var/lib/postgresql
  command: "true"
