# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-29 18:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtualmachines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='help',
            name='slug',
            field=models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='ID',
            field=models.TextField(blank=True, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='OS',
            field=models.TextField(blank=True, verbose_name='Operating System'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='about1',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='About1'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='about2',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='About2'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='appInstalls',
            field=models.TextField(blank=True, verbose_name='Applications Installed'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='description',
            field=models.TextField(blank=True, verbose_name='AMI Description'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='download',
            field=models.URLField(blank=True, verbose_name='Download URL'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='fileSize',
            field=models.TextField(blank=True, verbose_name='File Size'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='lastModified',
            field=models.DateTimeField(blank=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='lastTested',
            field=models.DateTimeField(blank=True, verbose_name='Last Tested'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='launch',
            field=models.URLField(blank=True, verbose_name='Launch URL'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='name',
            field=models.TextField(blank=True, verbose_name='AMI Name'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='notes',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='plugins',
            field=models.TextField(blank=True, verbose_name='Plugins'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='product1',
            field=models.CharField(blank=True, max_length=128, verbose_name='Product1 Name'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='product2',
            field=models.CharField(blank=True, max_length=128, verbose_name='Product2 Name'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='quickdownload',
            field=models.BooleanField(default=False, verbose_name='Quick Download from homepage?'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='quicklaunch',
            field=models.BooleanField(default=False, verbose_name='Quick Launch from homepage?'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='readMe',
            field=models.URLField(blank=True, verbose_name='ReadMe'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='server',
            field=models.TextField(blank=True, verbose_name='Server'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='serverAdditions',
            field=models.TextField(blank=True, verbose_name='Server Additions'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='slug',
            field=models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='website1',
            field=models.URLField(blank=True, verbose_name='Website1'),
        ),
        migrations.AlterField(
            model_name='specification',
            name='website2',
            field=models.URLField(blank=True, verbose_name='Website2'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='Suggested value automatically generated from title. Must be unique.', max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(help_text='Maximum 250 characters.', max_length=250),
        ),
        migrations.AlterField(
            model_name='type',
            name='slug',
            field=models.SlugField(blank=True, help_text='Suggested value automatically generated from title. Must be unique.', max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
