# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('virtualmachines', '0002_auto_20170829_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='help',
            old_name='displayName',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='home',
            old_name='displayName',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='ID',
            new_name='ami_id',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='appInstalls',
            new_name='app_installs',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='displayName',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='fileSize',
            new_name='file_size',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='lastModified',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='lastTested',
            new_name='last_tested',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='OS',
            new_name='os',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='quickdownload',
            new_name='quick_download',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='quicklaunch',
            new_name='quick_launch',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='serverAdditions',
            new_name='server_additions',
        ),
        migrations.RenameField(
            model_name='specification',
            old_name='userTests',
            new_name='user_tests',
        ),
    ]
