# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-09 18:41
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(help_text=b'Suggested value automatically generated from title. Must be unique.', max_length=100, unique=True, verbose_name=b'Slug')),
                ('about', ckeditor.fields.RichTextField(blank=True, verbose_name=b'About')),
            ],
            options={
                'verbose_name_plural': 'Library',
            },
        ),
    ]
