# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-29 18:02
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20160616_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='about',
            name='slug',
            field=models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='datePublished',
            field=models.DateTimeField(blank=True, verbose_name='Date Published'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='lastModified',
            field=models.DateTimeField(blank=True, verbose_name='Last Modified'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='slug',
            field=models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='influences',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='influences',
            name='slug',
            field=models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', max_length=100, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='About'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='project1',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Project1'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='project10',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Project10'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='project11',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Project11'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='project12',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Project12'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='project2',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Project2'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='project3',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Project3'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='project4',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Project4'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='project5',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Project5'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='project6',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Project6'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='project7',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Project7'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='project8',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Project8'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='project9',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='Project9'),
        ),
        migrations.AlterField(
            model_name='laboratory',
            name='slug',
            field=models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', max_length=100, unique=True, verbose_name='Slug'),
        ),
    ]
