# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20170829_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='displayName',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='datePublished',
            new_name='date_published',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='displayName',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='cv',
            old_name='lastModified',
            new_name='last_modified',
        ),
        migrations.RenameField(
            model_name='influences',
            old_name='displayName',
            new_name='display_name',
        ),
        migrations.RenameField(
            model_name='laboratory',
            old_name='displayName',
            new_name='display_name',
        ),
    ]
