# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-21 16:37
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20171218_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name=b'About'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name=b'Content'),
        ),
        migrations.AlterField(
            model_name='influences',
            name='about',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name=b'About'),
        ),
    ]
