# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-05 20:58
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20171221_1637'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(help_text=b'Suggested value automatically generated from title. Must be unique.', max_length=100, unique=True, verbose_name=b'Slug')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name=b'About')),
            ],
            options={
                'verbose_name_plural': 'Site Credits',
            },
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(help_text=b'Suggested value automatically generated from title. Must be unique.', max_length=100, unique=True, verbose_name=b'Slug')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name=b'About')),
            ],
            options={
                'verbose_name_plural': 'Site Design',
            },
        ),
        migrations.CreateModel(
            name='Publications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(help_text=b'Suggested value automatically generated from title. Must be unique.', max_length=100, unique=True, verbose_name=b'Slug')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name=b'About')),
            ],
            options={
                'verbose_name_plural': 'Publications',
            },
        ),
    ]
