# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_credits_design_publications'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cv',
        ),
    ]
