# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0009_auto_20180706_2001'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Laboratory',
            new_name='Projects',
        ),
        migrations.AlterModelOptions(
            name='projects',
            options={'verbose_name_plural': 'Projects'},
        ),
    ]
