# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-06 20:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20180706_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='project1',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project10',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project11',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project12',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project2',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project3',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project4',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project5',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project6',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project7',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project8',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='project9',
        ),
    ]
