# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_projects_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='position',
            field=models.IntegerField(default=1),
        ),
    ]
