# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-07 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0013_auto_20180707_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
