# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-28 20:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_auto_20180707_1534'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Publications',
            new_name='Writing',
        ),
        migrations.AlterModelOptions(
            name='writing',
            options={'verbose_name_plural': 'Writing'},
        ),
    ]
