# Generated by Django 2.2.3 on 2019-07-27 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20190721_1725'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Influences',
            new_name='Outputs',
        ),
        migrations.DeleteModel(
            name='Presentations',
        ),
        migrations.DeleteModel(
            name='Writing',
        ),
        migrations.AlterModelOptions(
            name='outputs',
            options={'verbose_name_plural': 'Outputs'},
        ),
    ]
