# Generated by Django 2.2.13 on 2020-11-10 20:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_auto_20201103_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(max_length=128)),
                ('slug', models.SlugField(help_text='Suggested value automatically generated from title. Must be unique.', max_length=100, unique=True, verbose_name='Slug')),
                ('about', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='About')),
            ],
            options={
                'verbose_name_plural': 'Talks',
            },
        ),
    ]
